### ISSUE TITLE
Missing 'batchrsp/items' field in JSON API response.

### ISSUE THREAD

**Issue by JohanWinther** [ORelio/Spotlight-Downloader#4] opened 2019-08-17 10:30 UTC
I get the following error message running `update-lockscreen.bat` or `update-wallpaper.bat`:
```
System.IO.InvalidDataException: SpotlightAPI: Missing 'batchrsp/items' field in JSON API response.
```

Has the API hit the download limit?

**Comment by ORelio** [comment] 2019-08-18 13:33
After trying out on my side, I could not reproduce your exact issue (which means the API response is invalid), but had some other issues due to connection droping, invalid image integrity and so on. Additionally, the API seems to return only 1 image instead of 6-7 as before.

If you face this error again and think your IP address may have been blacklisted, try opening the API URL in a web browser and checking the response: https://arc.msn.com/v3/Delivery/Cache?pid=209567&fmt=json&rafb=0&ua=WindowsShellClient%2F0&disphorzres=9999&dispvertres=9999&lo=80217&pl=en-US&lc=en-US&ctry=us&time=2017-12-31T23:59:59Z

To facilitate auto-downloading of the SpotlightArchive directory, I increased the limit of already downloaded images before giving up from 10 API requests to 50, and added retries with delay (3 retries by default) if an error is encountered when calling the API.

Additionally, to facilitate download if using a scheduled script to update wallpaper and lockscreen, 2 additional scripts have been added: they perform an API request and save the result to SpotlightArchive, then use the archive instead of a cache to set the wallpaper or lockscreen. This allows downloading Spotlight image slowly, without hammering the API, and automatically access all the images for offline use.

Please try out the latest release (v1.3) 🙂

**Comment by JohanWinther** [comment] 2019-08-18 15:59
I actually found out that I didn't get the errors when I disabled my VPN so perhaps the IP was blacklisted after all.

I'll try the new version and also check the link if the error occurs!

**Comment by ORelio** [comment] 2019-08-18 18:28
Good to hear. I'll close the issue for now, feel free to reopen later if needed 😉

**Closed by ORelio** 2019-08-18 18:28 UTC
