### ISSUE TITLE
SpotlightDL isn't working since 3 or 4 Days

### ISSUE THREAD

**Issue by potitpanda** [ORelio/Spotlight-Downloader#24] opened 2021-06-25 14:29 UTC
Hi 
SpotlightDL is down 
All Locales test fails.... 
Could you test from your computer ? 
Thanks

**Comment by ORelio** [comment] 2021-06-30 15:47
Hi,

I'm getting this from my computer:

![image](https://user-images.githubusercontent.com/1128206/123971232-27cfb400-d9ba-11eb-8334-0d4ff4ea319b.png)

It seems like Microsoft may have implemented rate limiting, but SpotlightDL simply wait and resume when an error happens, so it still works, although I'll consider putting a better error message in the next version if rate limiting indeed exists.

**Comment by potitpanda** [comment] 2021-06-30 16:15
af-NA ???

**Comment by ORelio** [comment] 2021-07-03 12:40
Hi,

af-NA works as expected.

![image](https://user-images.githubusercontent.com/1128206/124354494-89875c80-dc0c-11eb-9039-1cb7b9f82b18.png)

By the way, the rate limit seems to be gone.

**Comment by ORelio** [comment] 2021-07-09 20:54
Closing as could not reproduce.

**Closed by ORelio** 2021-07-09 20:54 UTC
